# Generated by cucumber-sinatra. (2014-01-02 16:00:50 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'github_stats.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = GitHubStats

class GitHubStatsWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  GitHubStatsWorld.new
end
